name = "capo-spinbonus-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=capo-spinbonus.es"
HMAC_KEY = "a103092f008f44e050f16f05217c101f7cf94e58bd130c3f0c0f8067adb61076"
COOKIE_NAME = "lnl"
PLAY_PATH = "play-now"
BUTTON_ID = "pb82f0f6198ceae2c90817bb87cc30481"
GATE_SALT = "b84878970fffa2cf"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0gd2"
CTA_SELECTOR = ".cta-955e9"
